// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjB4COdL8V1BQUdbOhu8mXv8wGrJ9RH04',
    appId: '1:270927301423:web:92c9060dae90d38e03afda',
    messagingSenderId: '270927301423',
    projectId: 'sample-4969d',
    authDomain: 'sample-4969d.firebaseapp.com',
    storageBucket: 'sample-4969d.firebasestorage.app',
    measurementId: 'G-CYYFPX597T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLkAWaG2DmJjRFt2r-WwkshnOLHFP2F-Q',
    appId: '1:270927301423:android:17d740183663e0e403afda',
    messagingSenderId: '270927301423',
    projectId: 'sample-4969d',
    storageBucket: 'sample-4969d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt2loB2sunpunfj6hAfD6f6R9ozaRVDd8',
    appId: '1:270927301423:ios:655e5fe842d667d203afda',
    messagingSenderId: '270927301423',
    projectId: 'sample-4969d',
    storageBucket: 'sample-4969d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt2loB2sunpunfj6hAfD6f6R9ozaRVDd8',
    appId: '1:270927301423:ios:655e5fe842d667d203afda',
    messagingSenderId: '270927301423',
    projectId: 'sample-4969d',
    storageBucket: 'sample-4969d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjB4COdL8V1BQUdbOhu8mXv8wGrJ9RH04',
    appId: '1:270927301423:web:3c71cea32708e99d03afda',
    messagingSenderId: '270927301423',
    projectId: 'sample-4969d',
    authDomain: 'sample-4969d.firebaseapp.com',
    storageBucket: 'sample-4969d.firebasestorage.app',
    measurementId: 'G-WM4HHH657P',
  );
}
